# Used for local testing

version: '3'

services:
  local-s3:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: test
      MINIO_SECRET_KEY: testtest
    command: server /data
    volumes:
      - s3-data:/data

volumes:
  s3-data:
